project:
  type: book
  output-dir: docs

lang: fr
book:
  cover-image : /figures/logo.png
  title: "TP Analyse spectrale"
  author: "Franck DAOUT"
  date: "02/10/2025"
  chapters:
    - index.qmd
    - TP_base_AS.qmd
    - TP_resolution_AS.qmd
    - TP_radar.qmd
    - TP_deux_implusions.qmd
    - FAQ.qmd

format:
  html:
    theme: cosmo
    number-depth: 2
  pdf:
    documentclass: scrreprt



